# Generated by Django 5.2.8 on 2026-03-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField(default=1, help_text='Amount of times to get CC Ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
            options={
                'db_table': 'collector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollectorInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector_app.collector')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'collectorinstance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollectorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ball')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='collector_app.collector')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
            options={
                'db_table': 'collectorrequirement',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['ball'], name='collector_ball_id_2a3b51_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['special'], name='collector_special_d7e7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['amount'], name='collector_amount_d44e07_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorinstance',
            index=models.Index(fields=['player'], name='collectorin_player__af558c_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorinstance',
            index=models.Index(fields=['collector'], name='collectorin_collect_0cbc6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectorinstance',
            unique_together={('player', 'collector')},
        ),
        migrations.AddIndex(
            model_name='collectorrequirement',
            index=models.Index(fields=['collector'], name='collectorre_collect_5decfd_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorrequirement',
            index=models.Index(fields=['ball'], name='collectorre_ball_id_01bf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorrequirement',
            index=models.Index(fields=['special'], name='collectorre_special_4c1993_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorrequirement',
            index=models.Index(fields=['amount'], name='collectorre_amount_39eca2_idx'),
        ),
    ]
