# Generated by Django 5.2.8 on 2026-03-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collector',
            name='collector_amount_d44e07_idx',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='amount',
        ),
    ]
