# Generated by Django 5.2.8 on 2026-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0002_remove_collector_collector_amount_d44e07_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date of this collector. If blank, collector is permanent', null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date of this collector. If blank, it starts immediately', null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='tradeable',
            field=models.BooleanField(default=True, help_text='Marks if all CC instances can be traded or not (default: true)'),
        ),
        migrations.AddField(
            model_name='collectorrequirement',
            name='delete_balls',
            field=models.BooleanField(default=False, help_text='If a user meets all requirements, will the required balls be removed? '),
        ),
    ]
