# Generated by Django 6.0 on 2026-09-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0020_playerdatadeletion"), ("collector_app", "0006_move_collectors_to_tier_1")]

    operations = [
        migrations.RemoveIndex(model_name="collector", name="collector_special_d7e7bb_idx"),
        migrations.AlterUniqueTogether(name="collectorinstance", unique_together=set()),
        migrations.AlterField(
            model_name="collectorinstance",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="collector_app.collectortierlevel",
            ),
        ),
        migrations.AlterField(
            model_name="collectorrequirement",
            name="delete_balls",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If a user meets all requirements, will the required balls be removed? Removed treasures are "
                    "never watched afterwards."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="collectorrequirement",
            name="level",
            field=models.ForeignKey(
                help_text="The tier this requirement belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="collector_app.collectortierlevel",
            ),
        ),
        migrations.AddIndex(
            model_name="collectorinstance",
            index=models.Index(fields=["monitored", "revoked_at"], name="collectorin_monitor_735b9e_idx"),
        ),
        migrations.AddConstraint(
            model_name="collectorinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("player", "collector", "level"),
                name="collectorinstance_active_unique",
            ),
        ),
        migrations.RemoveField(model_name="collector", name="special"),
        migrations.RemoveField(model_name="collector", name="tradeable"),
    ]
