# Generated by Django 6.0 on 2026-06-02 22:05


import tomllib
from pathlib import Path
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

config_path = Path(__file__).resolve().parents[3] / "ballsdex" / "packages" / "pack" / "config.toml"


def default_models_forward(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    PackSettings = apps.get_model("pack_models", "PackSettings")

    if not config_path.exists():
        PackSettings.objects.create(
            min_rarity_daily=50.0, max_rarity_daily=100.0, min_rarity_weekly=1.0, max_rarity_weekly=50.0
        )
        return

    with open(config_path, "rb") as f:
        data = tomllib.load(f)

    if data is None:
        PackSettings.objects.create(
            min_rarity_daily=50.0, max_rarity_daily=100.0, min_rarity_weekly=1.0, max_rarity_weekly=50.0
        )
        return

    daily = data.get("daily", {})
    weekly = data.get("weekly", {})

    PackSettings.objects.create(
        min_rarity_daily=daily.get("min_rarity_daily", 50.0),
        max_rarity_daily=daily.get("max_rarity_daily", 100.0),
        min_rarity_weekly=weekly.get("min_rarity_weekly", 1.0),
        max_rarity_weekly=weekly.get("max_rarity_weekly", 50.0),
    )


def default_models_backward(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    pass


class Migration(migrations.Migration):
    dependencies = [("pack_models", "0002_rename_uses_packresource_daily_uses_and_more")]

    operations = [
        migrations.CreateModel(
            name="PackSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_rarity_daily", models.FloatField(help_text="Lowest rarity that can appear in daily packs.")),
                ("max_rarity_daily", models.FloatField(help_text="Highest rarity that can appear in daily packs.")),
                ("min_rarity_weekly", models.FloatField(help_text="Lowest rarity that can appear in weekly packs.")),
                ("max_rarity_weekly", models.FloatField(help_text="Highest rarity that can appear in weekly packs.")),
            ],
            options={
                "db_table": "packsettings",
                "managed": True,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("min_rarity_daily__gte", 0)), name="packsettings_min_rarity_daily_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_rarity_daily__gte", 0)), name="packsettings_max_rarity_daily_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_rarity_weekly__gte", 0)), name="packsettings_min_rarity_weekly_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_rarity_weekly__gte", 0)), name="packsettings_max_rarity_weekly_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_rarity_daily__lte", models.F("max_rarity_daily"))),
                        name="packsettings_daily_min_lte_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_rarity_weekly__lte", models.F("max_rarity_weekly"))),
                        name="packsettings_weekly_min_lte_max",
                    ),
                ],
            },
        ),
        migrations.RunPython(code=default_models_forward, reverse_code=default_models_backward, atomic=True),
    ]
