# Generated by Django 6.0 on 2026-09-17 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pack_models", "0003_packsettings")]

    operations = [
        migrations.AddField(
            model_name="packresource",
            name="daily_bonus_rolled",
            field=models.BooleanField(
                default=False, help_text="Whether the chance of a bonus daily pack was already rolled this cycle."
            ),
        ),
        migrations.AddField(
            model_name="packresource",
            name="daily_bonus_uses",
            field=models.PositiveIntegerField(
                default=0, help_text="Bonus daily packs earned during the current cycle (luck or streak)."
            ),
        ),
        migrations.AddField(
            model_name="packresource", name="daily_cycle_started_at", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="packresource",
            name="daily_streak",
            field=models.PositiveIntegerField(
                default=0, help_text="How many daily cycles in a row the player opened daily packs."
            ),
        ),
        migrations.AddField(
            model_name="packsettings",
            name="bonus_daily_chance",
            field=models.FloatField(
                default=0,
                help_text="Chance, in percent, to unlock a bonus daily pack when opening the last daily pack of the "
                "day. Rolled once per day. Set to 0 to disable.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="packsettings",
            name="daily_uses",
            field=models.PositiveIntegerField(
                default=3, help_text="How many daily packs every player can open before the 24 hours cooldown."
            ),
        ),
        migrations.AddField(
            model_name="packsettings",
            name="streak_bonus_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Every time a player's daily pack streak reaches a multiple of this many days (7 = on day 7, "
                "14, 21...), they get a bonus daily pack that day. Set to 0 to disable.",
            ),
        ),
        migrations.AddField(
            model_name="packsettings",
            name="streak_grace_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="Players must open a daily pack again within this many hours after starting their previous "
                "day to keep their streak going. Past this window, the streak starts over.",
            ),
        ),
        migrations.CreateModel(
            name="PackBonusRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("server_id", models.BigIntegerField(help_text="Discord server ID the role belongs to.")),
                ("role_id", models.BigIntegerField(help_text="Role ID giving extra daily packs.")),
                (
                    "bonus_daily_uses",
                    models.PositiveIntegerField(
                        default=1, help_text="How many extra daily packs this role gives every day."
                    ),
                ),
            ],
            options={"db_table": "packbonusrole", "managed": True, "unique_together": {("server_id", "role_id")}},
        ),
    ]
