# Generated by Django 5.2.8 on 2026-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantitem',
            name='prize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
