# Generated by Django 5.2.8 on 2026-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0002_merchantitem_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('banner', models.ImageField(blank=True, help_text='An optional promotional banner for this shop.', null=True, upload_to='')),
                ('items', models.ManyToManyField(blank=True, to='merchant_app.merchantitem')),
            ],
            options={
                'db_table': 'globalshop',
                'managed': True,
            },
        ),
    ]
