# Generated by Django 6.0 on 2026-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0004_merchantsettings_token_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantitem',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text="How many of this item can still be bought, all players combined. It goes down with every purchase and the item can't be bought anymore once it reaches 0. Leave empty for an unlimited stock.", null=True),
        ),
    ]
