# Generated by Django 6.0 on 2026-09-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0020_playerdatadeletion"), ("merchant_app", "0005_merchantitem_stock")]

    operations = [
        migrations.AddField(
            model_name="merchantitem",
            name="per_player_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "How many of this item one player may ever buy. Counted per player and kept for good, so a limit "
                    "of 1 makes the item a one-off. It works on its own or alongside the shop stock above: with both, "
                    "the item runs out when either is reached. Leave empty for no limit."
                ),
                null=True,
                verbose_name="limit per player",
            ),
        ),
        migrations.CreateModel(
            name="MerchantPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField(default=0, help_text="How many the player has bought so far.")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="merchant_app.merchantitem",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_purchases",
                        to="bd_models.player",
                    ),
                ),
            ],
            options={"db_table": "merchantpurchase", "managed": True, "unique_together": {("player", "item")}},
        ),
    ]
