# Generated by Django 6.0 on 2026-09-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0020_playerdatadeletion"), ("eventpass_app", "0004_mandatory_quests_and_gifts")]

    operations = [
        migrations.AddField(
            model_name="eventpass",
            name="access_logic",
            field=models.CharField(
                choices=[("all", "All required"), ("any", "Any one required")],
                default="all",
                help_text="Whether a player must meet every condition below, or only one of them.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="eventpass",
            name="access_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown to a player who can't take part. Leave empty for the generated text.",
            ),
        ),
        migrations.AddField(
            model_name="playerpass",
            name="eligible",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether the player still meets the conditions of the pass. Rechecked every time they open "
                    "it; when it goes false, the quests that come back stop progressing, but what they already "
                    "finished is theirs."
                ),
            ),
        ),
        migrations.AddField(
            model_name="playerpass", name="eligible_checked_at", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="reward",
            name="mode",
            field=models.CharField(
                choices=[
                    ("all", "Give everything below"),
                    ("choice", "The player picks from the lines below"),
                    ("random", "Draw at random from the lines below"),
                ],
                default="all",
                help_text="Whether every line is given, the player picks among them, or they are drawn at random.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="offer",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text=(
                    "How many options a choice shows when the lines resolve to more than that (a group, a rarity "
                    "range...). 0 offers them all, up to the 25 Discord allows."
                ),
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="pick",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many are picked or drawn, for the two modes above. Ignored when everything is given.",
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="economy",
            field=models.ForeignKey(
                blank=True,
                help_text="Pool: this economy.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bd_models.economy",
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="exclude_balls",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pool: treasures never drawn, whatever the filters above say.",
                related_name="+",
                to="bd_models.ball",
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Pool: this group.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bd_models.ballgroup",
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="max_rarity",
            field=models.FloatField(
                blank=True,
                help_text="Pool: highest rarity value kept, which drops the most common treasures.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="min_rarity",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "Pool: lowest rarity value kept. A lower value is rarer, so this drops the rarest treasures — "
                    "10 leaves out everything rarer than T10."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rewardline",
            name="regime",
            field=models.ForeignKey(
                blank=True,
                help_text="Pool: this regime.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bd_models.regime",
            ),
        ),
        migrations.CreateModel(
            name="PassRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("role", "Have a Discord role"),
                            ("max_treasures", "Own at most this many treasures"),
                            ("min_treasures", "Own at least this many treasures"),
                            ("max_currency", "Have at most this many berries"),
                            ("min_currency", "Have at least this many berries"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "role_id",
                    models.BigIntegerField(
                        blank=True, help_text="Discord ID of the role, for a role condition.", null=True
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Only used to name the role in the message players read.",
                        max_length=64,
                    ),
                ),
                (
                    "count",
                    models.PositiveBigIntegerField(
                        default=0, help_text="The number of treasures or berries, for the others."
                    ),
                ),
                (
                    "event_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="access", to="eventpass_app.eventpass"
                    ),
                ),
            ],
            options={
                "verbose_name": "access condition",
                "verbose_name_plural": "access conditions",
                "db_table": "eventpassaccess",
                "ordering": ("pk",),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RewardChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", help_text="The quest or tier it came from.", max_length=128
                    ),
                ),
                ("options", models.JSONField(default=list, help_text="The treasures offered, as their ids.")),
                ("picks", models.PositiveSmallIntegerField(default=1, help_text="How many of them the player takes.")),
                ("chosen", models.JSONField(blank=True, default=list, help_text="What they took, as treasure ids.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="eventpass_app.eventpass",
                    ),
                ),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice",
                        to="eventpass_app.rewardgrant",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="bd_models.player"
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eventpass_app.reward",
                    ),
                ),
            ],
            options={
                "db_table": "eventpassrewardchoice",
                "ordering": ("pk",),
                "managed": True,
                "indexes": [models.Index(fields=["player", "resolved_at"], name="eventpass_choice_pending_idx")],
            },
        ),
    ]
