# Generated by Django 6.0 on 2026-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0005_pass_access_and_reward_choice")]

    operations = [
        migrations.AddField(
            model_name="playerpass",
            name="passed",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "The access conditions the player met at that check, as their ids. The ones that need Discord "
                    "(a role) can only be read there, so the engine reuses this answer for them and counts the "
                    "rest itself."
                ),
            ),
        )
    ]
