# Generated by Django 6.0 on 2026-09-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0020_playerdatadeletion"), ("eventpass_app", "0006_playerpass_passed_conditions")]

    operations = [
        migrations.AlterField(
            model_name="eventpass",
            name="emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Shown before the name. A server emoji is written in full, like <:StrawHat:1477078273078067252>."
                ),
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="eventpass",
            name="name",
            field=models.CharField(
                help_text=("Shown as the title of the pass, and how it is named in /pass view."),
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventpass",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (only staff can see it)"),
                    ("active", "Active"),
                    ("archived", "Archived (over, nothing can be claimed)"),
                ],
                default="draft",
                help_text=(
                    "A draft is only visible to staff and nothing progresses in it. Publish it to let players play, "
                    "and archive it to close it for good."
                ),
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="passrequirement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("role", "Have a Discord role"),
                    ("max_treasures", "Own at most this many treasures"),
                    ("min_treasures", "Own at least this many treasures"),
                    ("max_currency", "Have at most this many berries"),
                    ("min_currency", "Have at least this many berries"),
                ],
                help_text=("What the player must have to take part."),
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="passtier",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text=("Shown under the title, on the first page of the tier.")
            ),
        ),
        migrations.AlterField(
            model_name="passtier",
            name="emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text=("Shown before the name, written in full for a server emoji."),
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="passtier",
            name="name",
            field=models.CharField(
                help_text=("Shown as the title of the tier's page, and in its unlock text."), max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="playerquest",
            name="claimed_at",
            field=models.DateTimeField(blank=True, help_text="When the reward was handed over.", null=True),
        ),
        migrations.AlterField(
            model_name="playerquest",
            name="completed_at",
            field=models.DateTimeField(blank=True, help_text="When the goal was reached.", null=True),
        ),
        migrations.AlterField(
            model_name="playerquest",
            name="progress",
            field=models.PositiveBigIntegerField(default=0, help_text="How far the player is, against the goal."),
        ),
        migrations.AlterField(
            model_name="quest",
            name="ball",
            field=models.ForeignKey(
                blank=True,
                help_text=("Only count this treasure. Leave empty for any."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bd_models.ball",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text=("Shown before the name, written in full for a server emoji."),
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text=("Only count treasures of this group. Leave empty for any."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bd_models.ballgroup",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="name",
            field=models.CharField(
                help_text=("Shown to players, and used to point at the quest in a file."), max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                help_text=("Given when the quest is completed. A quest with no reward just counts towards the tier."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quests",
                to="eventpass_app.reward",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="special",
            field=models.ForeignKey(
                blank=True,
                help_text=("Only count treasures of this special. Leave empty for any."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bd_models.special",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, craft...)"),
                    ("command", "Use a command"),
                    ("trade", "Complete trades"),
                    ("trade_treasures", "Exchange treasures in trades"),
                    ("give_treasures", "Give treasures to players"),
                    ("friend", "Add friends"),
                    ("battle_win", "Win battles"),
                    ("give_currency", "Give berries to players"),
                    ("receive_currency", "Receive berries from players"),
                    ("catch_currency", "Earn berries by catching treasures"),
                    ("spend_currency", "Spend berries"),
                    ("craft", "Craft (claim a collector card)"),
                    ("pack_buy", "Buy packs"),
                    ("merchant_buy", "Buy from the merchant"),
                    ("shop_buy", "Buy from Buggy's shop"),
                    ("sell", "Sell treasures to Buggy"),
                    ("auction_create", "List treasures on the auction house"),
                    ("auction_bid", "Place bids on the auction house"),
                    ("auction_won", "Win auctions"),
                ],
                help_text=("What the player has to do. It decides which of the filters below are used."),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text=("Only used to recognise the bundle in the admin lists."),
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="rewardgrant",
            name="source",
            field=models.CharField(
                choices=[("quest", "Quest"), ("tier", "Tier"), ("final", "End of the pass")],
                help_text=("What the reward was given for."),
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="ball",
            field=models.ForeignKey(
                blank=True,
                help_text=("The treasure given. Leave empty to draw one from the pool below instead."),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bd_models.ball",
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="bonus_mode",
            field=models.CharField(
                choices=[
                    ("random", "Random, like a catch"),
                    ("fixed", "The values set below"),
                    ("zero", "No bonus (+0%)"),
                ],
                default="random",
                help_text=("How the attack and health bonuses of the treasure are rolled."),
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="frame_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    'Frame given to the treasure: its name ("Haki Aura") or the key it is stored under ("09-20-2026", '
                    'or "09-20-2026:3" for a frame of one special). A name is easier to read and does not change when '
                    "the event moves. Leave empty for a normal card."
                ),
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="kind",
            field=models.CharField(
                choices=[("berries", "Berries"), ("treasure", "Treasure")],
                default="treasure",
                help_text=("Berries are always given whatever the bundle's mode; only treasures are picked or drawn."),
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=0, help_text=("Lines are given, offered and listed from the lowest position.")
            ),
        ),
        migrations.AlterField(
            model_name="rewardline",
            name="special",
            field=models.ForeignKey(
                blank=True,
                help_text=("Special put on the treasure given. Leave empty for a regular one."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bd_models.special",
            ),
        ),
        migrations.AlterField(
            model_name="tierrequirement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("finish_previous", "Finish the previous tier (its mandatory quests)"),
                    ("quests_all", "Complete these quests"),
                    ("quests_count", "Complete a number of quests of the pass"),
                    ("previous_tier", "Unlock the previous tier"),
                    ("own_treasures", "Own treasures (tokens, a special...)"),
                    ("currency", "Have berries"),
                    ("date", "Wait until a date"),
                ],
                help_text=("What opens the tier. Only the fields that kind uses are read."),
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tierrequirement",
            name="special",
            field=models.ForeignKey(
                blank=True,
                help_text=("The special the owned treasures must have, for that kind of requirement."),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bd_models.special",
            ),
        ),
    ]
