# Generated by Django 6.0 on 2026-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0007_admin_help_text")]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="require_command_effect",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Only count the command when it actually did something. A /daily run while it is still on "
                    "cooldown, a shop with nothing left or a purchase the player could not afford then do not count. "
                    "Commands that never report an outcome are always counted."
                ),
                verbose_name="only count when it worked",
            ),
        )
    ]
