# Generated by Django 6.0 on 2026-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0009_streak_quest_types")]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, craft...)"),
                    ("command", "Use a command"),
                    ("trade", "Complete trades"),
                    ("trade_treasures", "Exchange treasures in trades"),
                    ("give_treasures", "Give treasures to players"),
                    ("friend", "Add friends"),
                    ("battle_win", "Win battles"),
                    ("give_currency", "Give berries to players"),
                    ("receive_currency", "Receive berries from players"),
                    ("catch_currency", "Earn berries by catching treasures"),
                    ("spend_currency", "Spend berries"),
                    ("craft", "Craft (claim a collector card)"),
                    ("pack_buy", "Buy packs"),
                    ("merchant_buy", "Buy from the merchant"),
                    ("shop_buy", "Buy from Buggy's shop"),
                    ("sell", "Sell treasures to Buggy"),
                    ("auction_create", "List treasures on the auction house"),
                    ("auction_bid", "Place bids on the auction house"),
                    ("auction_won", "Win auctions"),
                    ("currency_streak", "Reach a daily berry streak"),
                    ("pack_streak", "Reach a daily pack streak"),
                    ("own_treasures", "Own treasures (how many you have, not what you do)"),
                ],
                help_text="What the player has to do. It decides which of the filters below are used.",
                max_length=24,
            ),
        )
    ]
