# Generated by Django 6.0 on 2026-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0010_own_treasures_quest")]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="with_friend",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Only count it when the other player is on the friend list. A good way to give the friend "
                    "commands a reason to exist, since nothing else in the bot points at them."
                ),
                verbose_name="only with a friend",
            ),
        )
    ]
