# Generated by Django 6.0 on 2026-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0011_quest_with_friend")]

    operations = [
        migrations.AddField(
            model_name="eventpass",
            name="early_starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "An earlier date for the players meeting a condition marked as granting early access below. Leave "
                    "empty for a pass that opens for everybody at once."
                ),
                null=True,
                verbose_name="early start",
            ),
        ),
        migrations.AddField(
            model_name="passrequirement",
            name="grants_early_access",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "A player meeting this condition may start at the pass's early start date, before everybody else. "
                    "Ignored when the pass has no early start."
                ),
                verbose_name="lets them in early",
            ),
        ),
    ]
