# Generated by Django 6.0 on 2026-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0012_early_access")]

    operations = [
        migrations.AddField(
            model_name="passtier",
            name="announce",
            field=models.CharField(
                choices=[
                    ("public", "In the channel, where everyone sees it"),
                    ("ephemeral", "In the channel, but only the player sees it"),
                    ("private", "In the player's DMs only"),
                    ("none", "No message at all"),
                ],
                default="public",
                help_text=(
                    "Where the message goes when a player finishes this tier: in the channel for everyone, in the "
                    "channel but only for them, in their DMs, or nowhere. Finishing a tier is worth showing off, "
                    "so this is public by default even when the quests inside it are not."
                ),
                max_length=9,
                verbose_name="completion message",
            ),
        ),
        migrations.AddField(
            model_name="passtier",
            name="completion_message",
            field=models.TextField(
                blank=True, default="", help_text="Shown when the tier is finished. Leave empty for the default text."
            ),
        ),
    ]
