# Generated by Django 5.2.8 on 2025-12-01 17:20

from typing import TYPE_CHECKING, Literal, cast

from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.contrib.auth.models import Group, Permission
    from django.contrib.contenttypes.models import ContentType
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.models import Model

type perm_dict = dict["type[Model]", list[Literal["view", "add", "change", "delete"]] | Literal["*"]]


def get_permissions(
    permission_model: type["Permission"], content_type_model: type["ContentType"], permissions: perm_dict
) -> list["Permission"]:
    """
    Returns the list of permissions objects from a dictionnary mapping models to permission codes.
    """
    result: list["Permission"] = []
    for model, perms in permissions.items():
        content_type = content_type_model.objects.get_for_model(model)
        if perms == "*":
            perms = ["add", "change", "delete", "view"]
        for perm in perms:
            result.append(
                permission_model.objects.get(content_type=content_type, codename=f"{perm}_{model._meta.model_name}")
            )
    return result


def create_default_groups(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    group_model = cast(type["Group"], apps.get_model("auth", "Group"))
    permission_model = cast(type["Permission"], apps.get_model("auth", "Permission"))
    content_type_model = cast(type["ContentType"], apps.get_model("contenttypes", "ContentType"))

    Ball = apps.get_model("bd_models", "Ball")
    Regime = apps.get_model("bd_models", "Regime")
    Economy = apps.get_model("bd_models", "Economy")
    Special = apps.get_model("bd_models", "Special")
    BallInstance = apps.get_model("bd_models", "BallInstance")
    BlacklistedGuild = apps.get_model("bd_models", "BlacklistedGuild")
    BlacklistedID = apps.get_model("bd_models", "BlacklistedID")
    BlacklistHistory = apps.get_model("bd_models", "BlacklistHistory")
    Block = apps.get_model("bd_models", "Block")
    Friendship = apps.get_model("bd_models", "Friendship")
    GuildConfig = apps.get_model("bd_models", "GuildConfig")
    Player = apps.get_model("bd_models", "Player")
    Trade = apps.get_model("bd_models", "Trade")
    TradeObject = apps.get_model("bd_models", "TradeObject")

    staff_group, created = group_model.objects.get_or_create(name="Staff")
    if created:
        perms: perm_dict = {
            BallInstance: ["view"],
            BlacklistedGuild: "*",
            BlacklistedID: "*",
            BlacklistHistory: ["view"],
            Block: "*",
            Friendship: "*",
            GuildConfig: ["view", "change"],
            Player: ["view", "change"],
            Trade: ["view"],
            TradeObject: ["view"],
        }
        staff_group.permissions.add(*get_permissions(permission_model, content_type_model, perms))
    admin_group, created = group_model.objects.get_or_create(name="Admin")
    if created:
        perms: perm_dict = {
            Ball: "*",
            Regime: "*",
            Economy: "*",
            Special: "*",
            BallInstance: "*",
            BlacklistedGuild: "*",
            BlacklistedID: "*",
            BlacklistHistory: ["view"],
            Block: "*",
            Friendship: "*",
            GuildConfig: "*",
            Player: "*",
            Trade: ["view"],
            TradeObject: ["view"],
        }
        admin_group.permissions.add(*get_permissions(permission_model, content_type_model, perms))


def delete_default_groups(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    group_model = cast(type["Group"], apps.get_model("auth", "Group"))
    group_model.objects.filter(name__in=("Staff", "Admin")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("auth", "0011_update_proxy_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [migrations.RunPython(create_default_groups, delete_default_groups)]
