# Generated by Django 5.2.8 on 2026-02-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, help_text='An optional descripcion for this collectible', null=True)),
                ('emoji_id', models.BigIntegerField(help_text='Emoji ID of this collectible')),
                ('price', models.PositiveBigIntegerField(blank=True, help_text='The price of this collectible. If blanks, it will free.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('ball', models.ForeignKey(blank=True, help_text='An optional requirement that specifies a required ball.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ball')),
                ('special', models.ForeignKey(blank=True, help_text='An optional requirement that specifies a required special.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
            options={
                'verbose_name_plural': 'Collectibles',
                'db_table': 'collectible',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollectibleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectible_app.collectible')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to='bd_models.player')),
            ],
            options={
                'db_table': 'collectibleinstance',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='collectible',
            index=models.Index(fields=['name'], name='collectible_name_181e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='collectible',
            index=models.Index(fields=['ball'], name='collectible_ball_id_487ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='collectible',
            index=models.Index(fields=['special'], name='collectible_special_b082a0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectibleinstance',
            index=models.Index(fields=['player'], name='collectible_player__ab0dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='collectibleinstance',
            index=models.Index(fields=['collectible'], name='collectible_collect_4cb980_idx'),
        ),
    ]
