# WARNING: DO NOT EDIT THIS FILE DIRECTLY
# This file may be modified with future updates, changing it would break it
# You should copy the production.example.py file as "production.py" and place your settings there
# That file will not be tracked by git

import logging
import os
import pathlib
import sys
from pathlib import Path

import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = None

# WARNING: DO NOT ADD EXTERNAL HOSTS HERE!!
# If you want to expose your admin panel online, please follow this tutorial:
# https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Serving-the-admin-panel-online
# THIS HAS SECURITY IMPLICATIONS, ENABLES PRIVILEGE ESCALATION AND REMOTE CODE EXECUTION

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
INTERNAL_IPS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "admin_auto_filters",
    "django_admin_action_forms",
    "django_admin_inline_paginator",
    "social_django",
    "admin_panel.apps.BallsdexAdminConfig",
    "bd_models",
    "preview",
    "settings",
]

MIDDLEWARE = [
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "admin_panel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ]
        },
    }
]

WSGI_APPLICATION = "admin_panel.wsgi.application"

# Logging
if env_log_dir := os.environ.get("BALLSDEX_LOG_DIR"):
    log_dir = pathlib.Path(env_log_dir)
else:
    log_dir = pathlib.Path("./logs")
    if pathlib.Path("./manage.py").exists():
        log_dir = ".." / log_dir
    log_dir.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "bot_only": {"()": "admin_panel.logging.RequireBot"},
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
        "rich": {"()": "discord.utils._ColourFormatter"},
        "basic": {"format": "[{asctime}] {levelname} {name}: {message}", "datefmt": "%Y-%m-%d %H:%M:%S", "style": "{"},
    },
    "handlers": {
        "console": {"level": logging.DEBUG, "class": "logging.StreamHandler", "formatter": "rich"},
        "file": {
            "level": logging.INFO,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": log_dir / "ballsdex.log",
            "maxBytes": 8**7,
            "backupCount": 8,
            "formatter": "basic",
        },
        "buffer": {
            "level": logging.INFO,
            "class": "admin_panel.logging.DequeHandler",
            "filters": ["bot_only"],
            "formatter": "rich",
        },
        "webhook": {"level": logging.INFO, "class": "admin_panel.logging.WebhookHandler"},
        "django.server": {"level": logging.INFO, "class": "logging.StreamHandler", "formatter": "django.server"},
        "queue": {"class": "logging.handlers.QueueHandler", "handlers": ["console", "file", "webhook"]},
    },
    "loggers": {
        "root": {"handlers": ["queue", "buffer"], "level": logging.INFO},
        "uvicorn": {"handlers": ["queue"], "level": logging.INFO},
        "django.server": {"handlers": ["django.server"], "level": logging.INFO, "propagate": False},
        "aiohttp": {"level": logging.WARNING},
        "discord": {"level": logging.INFO},
        "django.db.backends": {
            "level": logging.DEBUG if os.environ.get("DATABASE_QUERY_LOG") else logging.INFO,
            "handlers": [],
        },
    },
}
LOGGING_CONFIG = "admin_panel.logging.setup_logging"
if "startbot" in sys.argv:
    SILENCED_SYSTEM_CHECKS = ["staticfiles.W004"]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": dj_database_url.config("BALLSDEXBOT_DB_URL")}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", "static")
STATICFILES_DIRS = ["staticfiles"]

MEDIA_URL = "media/"
MEDIA_ROOT = "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DISCORD_WEBHOOK_URL = None

# Django social auth settings
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "admin_panel.pipeline.configure_status",
)
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"

SOCIAL_AUTH_DISCORD_SCOPE = ["identify"]
AUTHENTICATION_BACKENDS = ["social_core.backends.discord.DiscordOAuth2", "django.contrib.auth.backends.ModelBackend"]
