# Generated by Django 6.0 on 2026-06-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0015_alter_ballinstance_server_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0, help_text='Amount of health to add')),
                ('attack', models.IntegerField(default=0, help_text='Amount of attack to add')),
                ('ball', models.OneToOneField(blank=True, help_text='Ball that will receive an increase', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('special', models.OneToOneField(blank=True, help_text='Specials that will receive an increase', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.special')),
            ],
            options={
                'db_table': 'buff',
                'managed': True,
            },
        ),
    ]
