# Generated by Django 6.0 on 2026-08-08 17:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0017_ballgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_url', models.URLField(default='https://top.gg/bot/1428438991203598467', help_text='Link shown to users to vote for the bot.')),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret configured on your Top.gg webhook page, used to verify the x-topgg-signature header of incoming vote webhooks. Leave empty to keep the webhook server disabled.', max_length=128)),
                ('min_rarity', models.FloatField(default=1.0, help_text='Lowest rarity that can be granted as a vote reward.')),
                ('max_rarity', models.FloatField(default=100.0, help_text='Highest rarity that can be granted as a vote reward.')),
                ('special_chance', models.FloatField(default=0.05, help_text='Chance (between 0 and 1) that the vote reward is a currently active special instead of a regular countryball.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name_plural': 'Vote settings',
                'db_table': 'votesettings',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('min_rarity__lte', models.F('max_rarity'))), name='vote_min_rarity_lte_max', violation_error_message='Minimum rarity must be lower or equal to maximum rarity.')],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='bd_models.player')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ballinstance')),
            ],
            options={
                'db_table': 'voterecord',
                'ordering': ('-voted_at',),
                'managed': True,
                'indexes': [models.Index(fields=['player_id', 'voted_at'], name='voterecord_player__b479a1_idx')],
            },
        ),
    ]
