# Generated by Django 5.2.8 on 2026-02-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='emoji_id',
            field=models.BigIntegerField(help_text='Emoji Id of the item', null=True),
        ),
    ]
