# Generated by Django 5.2.8 on 2026-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_item_ball_alter_item_maximum_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_amount',
            field=models.PositiveIntegerField(default=500, help_text='The amount of currency to give from a spawn.'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_chance',
            field=models.FloatField(default=0.2, help_text='Value between 0 and 1, chances to spawn currency.'),
        ),
    ]
