# Generated by Django 5.2.8 on 2026-04-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
        ('currency_app', '0005_currencysettings_spawn_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ball',
        ),
        migrations.CreateModel(
            name='ItemBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='currency_app.item')),
            ],
            options={
                'db_table': 'itemball',
                'managed': True,
            },
        ),
    ]
