# Generated by Django 6.0 on 2026-07-04 15:11

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def default_migrate_coins_forward(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    CurrencySettings = apps.get_model("currency_app", "CurrencySettings")
    MoneyInstance = apps.get_model("currency_app", "MoneyInstance")
    Player = apps.get_model("bd_models", "Player")
    Settings = apps.get_model("settings", "Settings")

    # migrate settings
    settings = Settings.objects.first()
    currency_settings = CurrencySettings.objects.first()
    if settings is not None and currency_settings is not None:
        update_fields = ["currency_name", "currency_plural_name"]
        settings.currency_name = currency_settings.name
        settings.currency_plural_name = currency_settings.plural_name
        if currency_settings.emoji_id is not None and hasattr(settings, "currency_emoji_id"):
            settings.currency_emoji_id = currency_settings.emoji_id
            update_fields.append("currency_emoji_id")
        settings.save(update_fields=update_fields)

    amounts = dict(MoneyInstance.objects.values_list("player_id", "amount"))
    players = list(Player.objects.filter(pk__in=amounts.keys()))
    for player in players:
        player.money = amounts[player.pk]
    Player.objects.bulk_update(players, ["money"])


def default_migrate_coins_backward(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("currency_app", "0006_remove_item_ball_itemball"),
        ("settings", "0007_settings_currency_emoji_id"),
        ("bd_models", "0016_alter_player_money"),
    ]

    operations = [migrations.RunPython(default_migrate_coins_forward, default_migrate_coins_backward, atomic=True)]
