# Generated by Django 6.0 on 2026-09-17 16:34

from django.db import migrations, models


def move_rarity_packs_to_tiers(apps, schema_editor):
    """Packs drawing from a rarity range (Bronze, Silver, Gold...) get their own /pack tiers command."""
    Item = apps.get_model("currency_app", "Item")
    Item.objects.filter(minimum_rarity__isnull=False, maximum_rarity__isnull=False).update(section="tiers")


class Migration(migrations.Migration):
    dependencies = [("currency_app", "0012_berrytransaction")]

    operations = [
        migrations.AlterModelOptions(
            name="item", options={"managed": True, "ordering": ("section", "position", "prize")}
        ),
        migrations.AddField(
            model_name="item",
            name="position",
            field=models.PositiveIntegerField(
                default=0, help_text="Packs are listed from the lowest position to the highest, then by price."
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="section",
            field=models.CharField(
                choices=[("shop", "Pack shop (/pack shop)"), ("tiers", "Tier packs (/pack tiers)")],
                default="shop",
                help_text="Which command lists this pack. Tier packs (Bronze, Silver, Gold...) have their own /pack "
                "tiers command so they don't get lost at the end of the shop.",
                max_length=8,
            ),
        ),
        migrations.RunPython(move_rarity_packs_to_tiers, migrations.RunPython.noop),
    ]
