# Generated by Django 5.2.8 on 2025-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0001_initial")]

    operations = [
        migrations.AddConstraint(
            model_name="promptmessage",
            constraint=models.UniqueConstraint(fields=("message", "category"), name="message_category_unique_together"),
        )
    ]
