# Generated by Django 6.0 on 2025-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0002_promptmessage_message_category_unique_together")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="currency_name",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Name of your currency. Warning: currency is disabled until you set this value. "
                "The core bot does not yet come with user-facing commands to manage currency.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="currency_plural_name",
            field=models.CharField(
                blank=True, default=None, help_text="Plural name of your currency.", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="currency_symbol",
            field=models.CharField(
                blank=True, default=None, help_text="A symbol for your currency.", max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="currency_symbol_before",
            field=models.BooleanField(
                default=False, help_text="If enabled, your currency symbol will be placed before the amount."
            ),
        ),
    ]
