# Generated by Django 6.0 on 2025-12-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0003_settings_currency_name_settings_currency_plural_name_and_more")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="site_base_url",
            field=models.URLField(
                default="http://localhost:8000", help_text="Base URL of this website, accessible with admin commands."
            ),
        )
    ]
