# Generated by Django 6.0 on 2026-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0004_settings_site_base_url")]

    operations = [
        migrations.AddField(
            model_name="promptmessage",
            name="rarity",
            field=models.FloatField(default=1.0, help_text="Weight of message."),
        )
    ]
