# Generated by Django 6.0 on 2026-04-06 17:22

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0005_promptmessage_rarity")]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="admin_channel_ids",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Semicolon-delimited channel IDs where staff may bypass inventory privacy. Ignored for owners.If empty, then admin commands can be used everywhere.",  # noqa: E501
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^(\\d{17,21}(;\\d{17,21})*)?$"), message="The IDs must be semicolon-separated"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="collectible_name",
            field=models.TextField(
                default="countryball",
                help_text="The singular name of your collectible",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-_'\\S]{1,32}$"), message="Invalid slash command name."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="plural_collectible_name",
            field=models.TextField(
                default="countryballs",
                help_text="The plural name of your collectible",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-_'\\S]{1,32}$"), message="Invalid slash command name."
                    )
                ],
            ),
        ),
    ]
