# Generated by Django 6.0 on 2026-04-04 06:14

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0005_promptmessage_rarity")]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="admin_channel_ids",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Semicolon-delimited channel IDs where staff may bypass inventory privacy. Ignored for owners.If empty, then admin commands can be used everywhere.",  # noqa: E501
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^(\\d{17,21}(;\\d{17,21})*)?$"), message="The IDs must be semicolon-separated"
                    )
                ],
            ),
        )
    ]
