# Generated by Django 6.0 on 2026-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0006_alter_settings_admin_channel_ids_and_more")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="currency_emoji_id",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="Optional emoji ID for your currency. When set, the emoji is shown instead of "
                "the currency name. The bot must have access to this emoji.",
                null=True,
            ),
        )
    ]
