# Generated by Django 6.0 on 2026-07-06 08:17

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0007_settings_currency_emoji_id")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="enabled_languages",
            field=models.TextField(
                default="en",
                help_text="Semicolon-separated list of language codes players and servers can select from "
                "(e.g. 'en;fr;es'). The first code is used as the fallback/default language.",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z]{2,3}(-[A-Za-z]{2,8})?(;[a-z]{2,3}(-[A-Za-z]{2,8})?)*$"),
                        message="Invalid language list.",
                    )
                ],
            ),
        )
    ]
