# Generated by Django 6.0 on 2026-08-07 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0007_settings_currency_emoji_id")]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(help_text="The tip to display below spawn messages")),
                ("enabled", models.BooleanField(default=True, help_text="Disabled tips are never picked.")),
                ("rarity", models.FloatField(default=1.0, help_text="Weight of tip.")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tips", to="settings.settings"
                    ),
                ),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("message",), name="tip_message_unique")]},
        ),
        migrations.AddField(
            model_name="settings",
            name="tip_chance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Percentage of spawns displaying a random tip below the message. A value of 10 means "
                "10% of spawns. Set to 0 to disable tips entirely. Server admins can also opt out individually.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tip_position",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Above the catch button"), (2, "Below the catch button")],
                default=1,
                help_text="Where the tip is placed within the spawn message.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tip_container",
            field=models.BooleanField(
                default=False,
                help_text="Whether to wrap the tip in a container, giving it a visible box instead of plain text.",
            ),
        ),
    ]
