# Generated by Django 6.0 on 2026-08-08 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_settings_currency_emoji_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vote_max_rarity',
            field=models.FloatField(default=100.0, help_text='Highest rarity that can be granted as a vote reward.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='vote_min_rarity',
            field=models.FloatField(default=1.0, help_text='Lowest rarity that can be granted as a vote reward.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='vote_special_chance',
            field=models.FloatField(default=0.05, help_text='Chance (between 0 and 1) that the vote reward is a currently active special instead of a regular countryball.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='vote_url',
            field=models.URLField(default='https://top.gg/bot/1428438991203598467', help_text='Link shown to users to vote for the bot.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='vote_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Secret configured on your Top.gg webhook page, used to verify the x-topgg-signature header of incoming vote webhooks. Leave empty to keep the /webhook/topgg endpoint disabled.', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(condition=models.Q(('vote_min_rarity__lte', models.F('vote_max_rarity'))), name='vote_min_rarity_lte_max', violation_error_message='Vote minimum rarity must be lower or equal to maximum rarity.'),
        ),
    ]
