# Generated by Django 6.0 on 2026-09-17 16:14

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='artist_credits_url',
            field=models.URLField(blank=True, default='', help_text='Link to the page crediting the artists (a GitHub file for instance). Shown in /about and when displaying a card.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='embed_color',
            field=models.CharField(default='#00FFFF', help_text='Hex color of every embed and message box sent by the bot, for instance #00FFFF for cyan.', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#[0-9a-fA-F]{6}$'), message='Enter a hex color such as #00FFFF.')]),
        ),
    ]
