# Generated by Django 6.0 on 2026-09-18 22:15

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0009_embed_color_and_artist_credits")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="catch_button_color",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Blurple"), (2, "Grey"), (3, "Green"), (4, "Red")],
                default=1,
                help_text="Color of the catch button.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="catch_button_emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji shown before the label: a unicode emoji like 🎯, a custom emoji like <:name:123456789012345678> or its ID. The bot's own emojis work, the others must come from a server the bot is in.",
                max_length=64,
                validators=[settings.models.validate_button_emoji],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="caught_button_color",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Blurple"), (2, "Grey"), (3, "Green"), (4, "Red")],
                default=1,
                help_text="Color of the button once caught.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="caught_button_emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji shown before the label: a unicode emoji like 🎯, a custom emoji like <:name:123456789012345678> or its ID. The bot's own emojis work, the others must come from a server the bot is in.",
                max_length=64,
                validators=[settings.models.validate_button_emoji],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="caught_button_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label of the button once caught, empty to keep the same.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="despawned_button_color",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Blurple"), (2, "Grey"), (3, "Green"), (4, "Red")],
                default=1,
                help_text="Color of the button once it left without being caught.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="despawned_button_emoji",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji shown before the label: a unicode emoji like 🎯, a custom emoji like <:name:123456789012345678> or its ID. The bot's own emojis work, the others must come from a server the bot is in.",
                max_length=64,
                validators=[settings.models.validate_button_emoji],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="despawned_button_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label of the button once it left without being caught, empty to keep the same.",
                max_length=80,
            ),
        ),
    ]
