# Generated by Django 6.0 on 2026-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0010_catch_button_looks")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="pass_auto_claim",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Give the reward of an event pass quest the moment it is completed, instead of waiting for the "
                    "player to press Claim. Tier and end-of-pass rewards keep their button: those are the moments "
                    "worth a click. A quest already set to give its reward right away does so either way."
                ),
                verbose_name="auto-claim event pass rewards",
            ),
        )
    ]
