# Generated by Django 6.0 on 2026-07-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0017_ballgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(help_text='128x128 PNG image', max_length=200, upload_to='')),
                ('type', models.CharField(choices=[('first_catch', 'First Catch'), ('first_special', 'First Special'), ('first_trade', 'First Trade'), ('first_battle', 'First Battle'), ('first_friend', 'First Friend'), ('first_favorite_ball', 'First Favorite Ball'), ('catch_ball', 'Catch Ball'), ('fastest_catcher', 'Fastest Catcher'), ('complete_trade', 'Complete Trade'), ('receive_ball', 'Receive Ball'), ('ball_count', 'Ball Count'), ('completion_percentage', 'Completion Percentage'), ('group_completed', 'Group Completed'), ('have_friend', 'Have X Friend'), ('playtime', 'Playtime'), ('actions', 'Actions (event-triggered)')], max_length=48)),
                ('prerequisite_logic', models.CharField(choices=[('all', 'All required'), ('any', 'Any one Required')], default='all', max_length=3)),
                ('target_value', models.PositiveBigIntegerField()),
                ('extra_params', models.JSONField(blank=True, default=dict)),
                ('ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ball')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ballgroup')),
                ('prerequisities', models.ManyToManyField(blank=True, to='achievement_app.achievement')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
            options={
                'db_table': 'achievement',
                'managed': True,
            },
        ),
    ]
