# Generated by Django 6.0 on 2026-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='128x128 PNG image', max_length=200, null=True, upload_to=''),
        ),
    ]
