# Generated by Django 6.0 on 2026-07-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement_app', '0002_alter_achievement_thumbnail'),
        ('bd_models', '0017_ballgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='currency_reward',
            field=models.PositiveIntegerField(db_default=0, help_text='When a user completes the achievement, how much currency gets?'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('first_catch', 'First Catch'), ('first_special', 'First Special'), ('first_trade', 'First Trade'), ('first_battle', 'First Battle'), ('first_friend', 'First Friend'), ('first_favorite_ball', 'First Favorite Ball'), ('catch_ball', 'Catch Ball'), ('fastest_catcher', 'Fastest Catcher'), ('complete_trade', 'Complete Trade'), ('receive_ball', 'Receive Ball'), ('ball_count', 'Ball Count'), ('completion_percentage', 'Completion Percentage'), ('group_completed', 'Group Completed'), ('have_friend', 'Have X Friend'), ('playtime', 'Playtime'), ('actions', 'Actions (event-triggered)'), ('complete_group', 'Catch all balls from a Group')], max_length=48),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement_app.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'userachievement',
                'managed': True,
                'indexes': [models.Index(fields=['player_id'], name='userachieve_player__de6d09_idx'), models.Index(fields=['achievement_id'], name='userachieve_achieve_11792a_idx')],
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
