# Generated by Django 6.0 on 2026-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement_app', '0003_achievement_currency_reward_alter_achievement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='required_value',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('first_catch', 'First Catch'), ('first_special', 'First Special'), ('first_trade', 'First Trade'), ('first_battle', 'First Battle'), ('first_friend', 'First Friend'), ('first_favorite_ball', 'First Favorite Ball'), ('catch_ball', 'Catch Ball'), ('fastest_catcher', 'Fastest Catcher'), ('complete_trade', 'Complete Trade'), ('receive_ball', 'Receive Ball'), ('ball_count', 'Ball Count'), ('completion_percentage', 'Completion Percentage'), ('have_friend', 'Have X Friend'), ('playtime', 'Playtime'), ('actions', 'Actions (event-triggered)'), ('complete_group', 'Catch all balls from a Group')], max_length=48),
        ),
    ]
