# Generated by Django 6.0 on 2026-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement_app', '0004_achievement_required_value_alter_achievement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='required_value',
            field=models.PositiveBigIntegerField(blank=True, help_text='Threshold each individual event must meet to count (Only for Fastest Catcher and Complete Trade with Currency)', null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='target_value',
            field=models.PositiveBigIntegerField(help_text='Total progress needed to complete this achievement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('first_catch', 'First Catch'), ('first_special', 'First Special'), ('first_trade', 'First Trade'), ('first_battle', 'First Battle'), ('first_friend', 'First Friend'), ('first_favorite_ball', 'First Favorite Ball'), ('catch_ball', 'Catch Ball'), ('fastest_catcher', 'Fastest Catcher'), ('complete_trade', 'Complete Trade'), ('receive_ball', 'Receive Ball'), ('ball_count', 'Ball Count'), ('completion_percentage', 'Completion Percentage'), ('have_friend', 'Have X Friend'), ('actions', 'Actions (event-triggered)'), ('complete_group', 'Catch all balls from a Group'), ('playtime', 'Time using the bot')], max_length=48),
        ),
    ]
