# Generated by Django 6.0 on 2026-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("achievement_app", "0007_convert_achievements_to_v2")]

    operations = [
        migrations.AlterModelOptions(
            name="achievement", options={"managed": True, "ordering": ("category__position", "position", "name")}
        ),
        migrations.RemoveField(model_name="achievement", name="extra_params"),
        migrations.RemoveField(model_name="achievement", name="required_value"),
        migrations.AlterField(
            model_name="achievement", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)
        ),
        migrations.AlterField(
            model_name="achievement",
            name="currency_reward",
            field=models.PositiveIntegerField(db_default=0, default=0, help_text="Currency given on unlock."),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Shown to players. Leave empty to show the goal generated from the settings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="prerequisities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Achievements that must be unlocked before this one starts progressing.",
                to="achievement_app.achievement",
                verbose_name="prerequisites",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="target_value",
            field=models.PositiveBigIntegerField(
                help_text="How much progress is needed, the unit depends on the type.", verbose_name="goal"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, claim...)"),
                    ("own", "Own treasures at the same time"),
                    ("complete_group", "Complete a group"),
                    ("completion", "Reach a completion percentage"),
                    ("trade", "Complete trades"),
                    ("friends", "Have friends"),
                    ("favorites", "Have favorite treasures"),
                    ("battle_win", "Win battles"),
                    ("playtime", "Play since the first catch"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="achievement", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)
        ),
    ]
