# Generated by Django 6.0 on 2026-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("achievement_app", "0008_achievements_v2_cleanup")]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="command_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Full name of the slash command, without the slash: "treasures list" to open the inventory.',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="min_currency",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Only count trades or gifts where the player receives at least this much currency.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="partner_discord_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Only count trades with this Discord user, or the currency this user gives (ID).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, claim...)"),
                    ("own", "Own treasures at the same time"),
                    ("complete_group", "Complete a group"),
                    ("completion", "Reach a completion percentage"),
                    ("trade", "Complete trades"),
                    ("friends", "Have friends"),
                    ("favorites", "Have favorite treasures"),
                    ("battle_win", "Win battles"),
                    ("playtime", "Play since the first catch"),
                    ("command", "Use a command"),
                    ("receive_currency", "Receive currency from someone"),
                ],
                max_length=48,
            ),
        ),
    ]
