# Generated by Django 6.0 on 2026-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("achievement_app", "0009_command_and_currency_achievements")]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="in_one_trade",
            field=models.BooleanField(
                default=False, help_text="Ask for a single trade exchanging that many treasures, instead of a total."
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, claim...)"),
                    ("own", "Own treasures at the same time"),
                    ("complete_group", "Complete a group"),
                    ("completion", "Reach a completion percentage"),
                    ("trade", "Complete trades"),
                    ("trade_treasures", "Exchange treasures in trades"),
                    ("friends", "Have friends"),
                    ("favorites", "Have favorite treasures"),
                    ("battle_win", "Win battles"),
                    ("playtime", "Play since the first catch"),
                    ("command", "Use a command"),
                    ("receive_currency", "Receive currency from someone"),
                ],
                max_length=48,
            ),
        ),
    ]
