# Generated by Django 6.0 on 2026-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("achievement_app", "0010_trade_treasures_achievement")]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="in_one_trade",
            field=models.BooleanField(
                default=False,
                help_text="Ask for that many treasures in a single trade or donation, instead of adding them up.",
                verbose_name="in one go",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="partner_discord_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Only count what involves this Discord user (ID): the trade partner, the one giving the "
                "currency, or the one receiving the treasures.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("catch", "Catch treasures"),
                    ("obtain", "Obtain treasures (catch, trade, pack, claim...)"),
                    ("own", "Own treasures at the same time"),
                    ("complete_group", "Complete a group"),
                    ("completion", "Reach a completion percentage"),
                    ("trade", "Complete trades"),
                    ("trade_treasures", "Exchange treasures in trades"),
                    ("give_treasures", "Give treasures to players"),
                    ("friends", "Have friends"),
                    ("favorites", "Have favorite treasures"),
                    ("battle_win", "Win battles"),
                    ("playtime", "Play since the first catch"),
                    ("command", "Use a command"),
                    ("receive_currency", "Receive currency from someone"),
                ],
                max_length=48,
            ),
        ),
    ]
