-- upgrade --
ALTER TABLE "ball" ALTER COLUMN "economy_id" TYPE INT USING "economy_id"::INT;
ALTER TABLE "ball" ALTER COLUMN "regime_id" TYPE INT USING "regime_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "trade_player_id" TYPE INT USING "trade_player_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "player_id" TYPE INT USING "player_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "special_id" TYPE INT USING "special_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "ball_id" TYPE INT USING "ball_id"::INT;
ALTER TABLE "player" ADD "mention_policy" SMALLINT NOT NULL  DEFAULT 1;
ALTER TABLE "player" DROP COLUMN "coins";
ALTER TABLE "trade" DROP COLUMN "player2_coins";
ALTER TABLE "trade" DROP COLUMN "player1_coins";
ALTER TABLE "trade" ALTER COLUMN "player1_id" TYPE INT USING "player1_id"::INT;
ALTER TABLE "trade" ALTER COLUMN "player2_id" TYPE INT USING "player2_id"::INT;
ALTER TABLE "tradeobject" ALTER COLUMN "player_id" TYPE INT USING "player_id"::INT;
ALTER TABLE "tradeobject" ALTER COLUMN "trade_id" TYPE INT USING "trade_id"::INT;
ALTER TABLE "tradeobject" ALTER COLUMN "ballinstance_id" TYPE INT USING "ballinstance_id"::INT;
-- downgrade --
ALTER TABLE "ball" ALTER COLUMN "economy_id" TYPE INT USING "economy_id"::INT;
ALTER TABLE "ball" ALTER COLUMN "regime_id" TYPE INT USING "regime_id"::INT;
ALTER TABLE "trade" ADD "player2_coins" INT NOT NULL  DEFAULT 0;
ALTER TABLE "trade" ADD "player1_coins" INT NOT NULL  DEFAULT 0;
ALTER TABLE "trade" ALTER COLUMN "player1_id" TYPE INT USING "player1_id"::INT;
ALTER TABLE "trade" ALTER COLUMN "player2_id" TYPE INT USING "player2_id"::INT;
ALTER TABLE "player" ADD "coins" INT NOT NULL  DEFAULT 0;
ALTER TABLE "player" DROP COLUMN "mention_policy";
ALTER TABLE "tradeobject" ALTER COLUMN "player_id" TYPE INT USING "player_id"::INT;
ALTER TABLE "tradeobject" ALTER COLUMN "trade_id" TYPE INT USING "trade_id"::INT;
ALTER TABLE "tradeobject" ALTER COLUMN "ballinstance_id" TYPE INT USING "ballinstance_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "trade_player_id" TYPE INT USING "trade_player_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "player_id" TYPE INT USING "player_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "special_id" TYPE INT USING "special_id"::INT;
ALTER TABLE "ballinstance" ALTER COLUMN "ball_id" TYPE INT USING "ball_id"::INT;
