-- upgrade --
CREATE TABLE IF NOT EXISTS "friendship" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "since" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "player1_id" INT NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "player2_id" INT NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "block" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "date" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "player1_id" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "player2_id" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE
);
-- downgrade --
DROP TABLE IF EXISTS "friendship";
DROP TABLE IF EXISTS "block";
