# Generated by Django 5.1.4 on 2025-01-28 14:44

import sys
from typing import TYPE_CHECKING

from django.db import connection, migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def execute_aerich_migration_check(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT EXISTS(SELECT * FROM information_schema.tables "
            "WHERE table_schema = 'public' AND table_name = 'aerich')"
        )
        has_aerich = cursor.fetchone()
        assert has_aerich
        if not has_aerich[0]:
            # aerich presence not detected, new instance, keep going
            return

        cursor.execute("SELECT version FROM aerich ORDER BY id DESC")
        version = cursor.fetchone()
        assert version
        if version[0] != "38_20250120182312_update.sql":
            raise RuntimeError(
                "Aerich migrations exists and are not up to date, cannot safely proceed!!\n\n"
                "The old migration engine is being removed in favor of Django's own, you must "
                "either have an empty table or have a perfectly up-to-date database to migrate.\n"
                "The resolution is to roll back to version 2.24.2, run the bot once to complete "
                "all migrations, then upgrade to the latest version.\n\n"
                "Commands to run:\n"
                "  git checkout release/2.24.2\n"
                "  docker compose up --build bot\n"
                '  [Press Ctrl+C after seeing the line "Ran X migrations: ...."]\n'
                "  git switch -\n"
                "  docker compose up --build admin-panel\n"
                "  [Ensure all migrations complete successfully]"
            )
        elif "--fake-initial" not in sys.argv:
            raise RuntimeError(
                "Detected up-to-date Aerich table but --fake-initial flag missing\n\n"
                "You are about to migrate from the Aerich migration engine to Django's own. "
                "Your database is up-to-date, but you must run this command with the "
                "--fake-initial flag to instruct Django to not override existing tables.\n\n"
                'Please run "python3 manage.py migrate --fake-initial" to pass this migration.'
            )


def aerich_move_backwards(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    # allows reversing the migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0002_move_upload_files"),
    ]

    operations = [
        migrations.RunPython(
            code=execute_aerich_migration_check,
            reverse_code=aerich_move_backwards,
        ),
        migrations.DeleteModel(
            name="Ball",
        ),
        migrations.DeleteModel(
            name="BallInstance",
        ),
        migrations.DeleteModel(
            name="BlacklistedGuild",
        ),
        migrations.DeleteModel(
            name="BlacklistedID",
        ),
        migrations.DeleteModel(
            name="BlacklistHistory",
        ),
        migrations.DeleteModel(
            name="Block",
        ),
        migrations.DeleteModel(
            name="Economy",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="Guildconfig",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="Regime",
        ),
        migrations.DeleteModel(
            name="Special",
        ),
        migrations.DeleteModel(
            name="Trade",
        ),
        migrations.DeleteModel(
            name="Tradeobject",
        ),
    ]
