# Generated by Django 5.1.4 on 2025-01-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0002_move_upload_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ball",
        ),
        migrations.DeleteModel(
            name="BallInstance",
        ),
        migrations.DeleteModel(
            name="BlacklistedGuild",
        ),
        migrations.DeleteModel(
            name="BlacklistedID",
        ),
        migrations.DeleteModel(
            name="BlacklistHistory",
        ),
        migrations.DeleteModel(
            name="Block",
        ),
        migrations.DeleteModel(
            name="Economy",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="Guildconfig",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="Regime",
        ),
        migrations.DeleteModel(
            name="Special",
        ),
        migrations.DeleteModel(
            name="Trade",
        ),
        migrations.DeleteModel(
            name="Tradeobject",
        ),
    ]
