# Generated by Django 5.1.4 on 2025-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0004_check_aerich_migrations_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="credits",
            field=models.CharField(
                help_text="Author of the special event artwork", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ball",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="An alternative shorter name used only when generating the card, if "
                "the base name is too long.",
                max_length=24,
                null=True,
            ),
        ),
    ]
