# Generated by Django 5.1.4 on 2025-02-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0005_alter_ball_short_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ball",
            old_name="capacity_description",
            new_name="ability_description",
        ),
        migrations.RenameField(
            model_name="ball",
            old_name="capacity_logic",
            new_name="ability_logic",
        ),
        migrations.RenameField(
            model_name="ball",
            old_name="capacity_name",
            new_name="ability_name",
        ),
    ]
