# Generated by Django 5.1.4 on 2025-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0005_alter_ball_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="accepted_tos",
            field=models.BooleanField(
                default=False, help_text="Whether you've accepted the TOS or not"
            ),
        ),
    ]
