# Generated by Django 5.1.4 on 2025-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0005_alter_ball_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
