# Generated by Django 5.1.4 on 2025-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0005_alter_ball_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
