# Generated by Django 5.1.4 on 2025-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0005_alter_ball_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="money",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Money posessed by the player"
            ),
        ),
    ]
