# Generated by Django 5.1.4 on 2025-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0007_player_trade_cooldown_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballinstance',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this instance was deleted or not. '),
        )
    ]
