# Generated by Django 5.1.4 on 2025-07-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0007_player_trade_cooldown_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("template", models.JSONField(help_text="Card template JSON")),
            ],
            options={
                "verbose_name_plural": "card templates",
                "db_table": "cardtemplate",
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="ball",
            options={
                "managed": True,
                "verbose_name": "countryball",
                "verbose_name_plural": "countryballs",
            },
        ),
        migrations.AlterModelOptions(
            name="ballinstance",
            options={"managed": True, "verbose_name": "countryball instance"},
        ),
        migrations.AlterField(
            model_name="ball",
            name="country",
            field=models.CharField(max_length=48, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="regime",
            name="card_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Card template to use",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bd_models.cardtemplate",
            ),
        ),
        migrations.AddField(
            model_name="special",
            name="card_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Card template to use",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bd_models.cardtemplate",
            ),
        ),
    ]
