# Generated by Django 5.1.4 on 2025-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0007_player_trade_cooldown_policy")]

    operations = [
        migrations.AddField(
            model_name="player",
            name="money",
            field=models.PositiveBigIntegerField(default=0, help_text="Money posessed by the player"),
        ),
        migrations.AddField(model_name="trade", name="player1_money", field=models.PositiveBigIntegerField(default=0)),
        migrations.AddField(model_name="trade", name="player2_money", field=models.PositiveBigIntegerField(default=0)),
    ]
