# Generated by Django 5.2.8 on 2026-01-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0009_ballinstance_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="club",
            field=models.CharField(
                blank=True, help_text="Current club of the player", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="ball",
            name="nationality",
            field=models.CharField(
                blank=True, help_text="Nationality of the player", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="ball",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Player position: GK, DEF, MID, or FWD",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ball",
            name="rarity_tier",
            field=models.CharField(
                default="common",
                help_text="Rarity tier: common, rare, epic, or legendary",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ball",
            name="rating",
            field=models.IntegerField(default=50, help_text="Player rating from 1-99"),
        ),
        migrations.CreateModel(
            name="UserPacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "common_packs",
                    models.IntegerField(default=0, help_text="Number of common packs"),
                ),
                ("rare_packs", models.IntegerField(default=0, help_text="Number of rare packs")),
                ("epic_packs", models.IntegerField(default=0, help_text="Number of epic packs")),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="bd_models.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Packs",
                "verbose_name_plural": "User Packs",
                "db_table": "userpacks",
                "managed": True,
            },
        ),
    ]
