# Generated by Django 5.1.4 on 2025-04-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0009_player_money_trade_player1_money_trade_player2_money")]

    operations = [
        migrations.AlterField(model_name="ballinstance", name="attack_bonus", field=models.IntegerField(default=0)),
        migrations.AlterField(
            model_name="ballinstance", name="catch_date", field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AlterField(model_name="ballinstance", name="favorite", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="ballinstance", name="health_bonus", field=models.IntegerField(default=0)),
        migrations.AlterField(
            model_name="ballinstance",
            name="locked",
            field=models.DateTimeField(
                default=None, help_text="If the instance was locked for a trade and when", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="balls", to="bd_models.player"
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="server_id",
            field=models.BigIntegerField(help_text="Discord server ID where this ball was caught", null=True),
        ),
        migrations.AlterField(model_name="ballinstance", name="spawned_time", field=models.DateTimeField(null=True)),
        migrations.AlterField(
            model_name="ballinstance",
            name="special",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.special"),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="trade_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ballinstance_trade_player_set",
                to="bd_models.player",
            ),
        ),
        migrations.AlterField(model_name="ballinstance", name="tradeable", field=models.BooleanField(default=True)),
        migrations.AlterField(
            model_name="blacklistedguild",
            name="moderator_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="blacklistedguild", name="reason", field=models.TextField(blank=True, default=None, null=True)
        ),
        migrations.AlterField(
            model_name="blacklistedid",
            name="moderator_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="blacklistedid", name="reason", field=models.TextField(blank=True, default=None, null=True)
        ),
        migrations.AlterField(
            model_name="guildconfig",
            name="enabled",
            field=models.BooleanField(default=True, help_text="Whether the bot will spawn countryballs in this guild"),
        ),
        migrations.AlterField(
            model_name="guildconfig",
            name="silent",
            field=models.BooleanField(
                default=False, help_text="Whether the responses of guesses get sent as ephemeral or not"
            ),
        ),
        migrations.AlterField(
            model_name="guildconfig",
            name="spawn_channel",
            field=models.BigIntegerField(help_text="Discord channel ID where balls will spawn", null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="donation_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Always Accept"), (2, "Request Approval"), (3, "Always Deny"), (4, "Friends Only")],
                default=1,
                help_text="How you want to handle donations",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="friend_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Allow"), (2, "Deny")], default=1, help_text="Open or close your friend requests"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="mention_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Allow"), (2, "Deny")], default=1, help_text="Control the bot's mentions"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="privacy_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Allow"), (2, "Deny"), (3, "Same Server"), (4, "Friends")],
                default=2,
                help_text="How you want to handle inventory privacy",
            ),
        ),
        migrations.AddIndex(
            model_name="ballinstance", index=models.Index(fields=["ball_id"], name="ballinstanc_ball_id_2d5440_idx")
        ),
        migrations.AddIndex(
            model_name="ballinstance", index=models.Index(fields=["player_id"], name="ballinstanc_player__9c7405_idx")
        ),
        migrations.AddIndex(
            model_name="ballinstance", index=models.Index(fields=["special_id"], name="ballinstanc_special_612f01_idx")
        ),
        migrations.AddIndex(
            model_name="trade", index=models.Index(fields=["player1_id"], name="trade_player1_3c0ba4_idx")
        ),
        migrations.AddIndex(
            model_name="trade", index=models.Index(fields=["player2_id"], name="trade_player2_c82825_idx")
        ),
        migrations.AddIndex(
            model_name="tradeobject",
            index=models.Index(fields=["ballinstance_id"], name="tradeobject_ballins_64d733_idx"),
        ),
        migrations.AddIndex(
            model_name="tradeobject", index=models.Index(fields=["player_id"], name="tradeobject_player__fda68c_idx")
        ),
        migrations.AddIndex(
            model_name="tradeobject", index=models.Index(fields=["trade_id"], name="tradeobject_trade_i_1eed3d_idx")
        ),
    ]
