# Generated by Django 5.2.1 on 2025-06-13 13:43

from typing import TYPE_CHECKING

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_perms(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    content_type, _ = ContentType.objects.get_or_create(app_label="admincmd", model="Admin")
    Permission.objects.get_or_create(codename="logs", name="Can use /admin logs", content_type=content_type)


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0009_alter_ballinstance_attack_bonus_and_more")]

    operations = [migrations.RunPython(create_perms, reverse_code=migrations.RunPython.noop)]
