# Generated by Django 5.2.8 on 2026-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0010_ball_club_ball_nationality_ball_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="defending",
            field=models.IntegerField(default=50, help_text="DEF - Defending ability"),
        ),
        migrations.AddField(
            model_name="ball",
            name="dribbling",
            field=models.IntegerField(default=50, help_text="DRI - Dribbling skills"),
        ),
        migrations.AddField(
            model_name="ball",
            name="pace",
            field=models.IntegerField(default=50, help_text="PAC - Player pace/speed"),
        ),
        migrations.AddField(
            model_name="ball",
            name="passing",
            field=models.IntegerField(default=50, help_text="PAS - Passing ability"),
        ),
        migrations.AddField(
            model_name="ball",
            name="physical",
            field=models.IntegerField(default=50, help_text="PHY - Physical strength"),
        ),
        migrations.AddField(
            model_name="ball",
            name="shooting",
            field=models.IntegerField(default=50, help_text="SHO - Shooting ability"),
        ),
    ]
