# Generated by Django 6.0 on 2026-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0011_ball_defending_ball_dribbling_ball_pace_ball_passing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ball",
            options={
                "managed": True,
                "verbose_name": "countryball",
                "verbose_name_plural": "countryballs",
            },
        ),
        migrations.AlterModelOptions(
            name="ballinstance",
            options={"managed": True, "verbose_name": "countryball instance"},
        ),
        migrations.AddField(
            model_name="userpacks",
            name="last_daily_claim",
            field=models.DateTimeField(
                blank=True, help_text="Last time the user claimed their daily pack", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpacks",
            name="last_weekly_claim",
            field=models.DateTimeField(
                blank=True, help_text="Last time the user claimed their weekly pack", null=True
            ),
        ),
    ]
