# Generated by Django 5.2.7 on 2025-11-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0011_alter_ballinstance_attack_bonus_and_more")]

    operations = [
        migrations.AlterField(
            model_name="ballinstance",
            name="locked",
            field=models.DateTimeField(
                blank=True, default=None, help_text="If the instance was locked for a trade and when", null=True
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="trade_cooldown_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Cooldown"), (2, "Bypass")], default=1, help_text="To bypass or not the trade cooldown"
            ),
        ),
    ]
