# Generated by Django 5.2.7 on 2025-11-17 15:14
from typing import TYPE_CHECKING

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_perms(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    content_type, _ = ContentType.objects.get_or_create(app_label="admincmd", model="Admin")
    Permission.objects.get_or_create(codename="logs", name="Can use /admin logs", content_type=content_type)


class Migration(migrations.Migration):
    dependencies = [
        ("bd_models", "0012_alter_ballinstance_locked_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [migrations.RunPython(create_perms, reverse_code=migrations.RunPython.noop)]
