# Generated by Django 5.2.8 on 2025-11-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0013_auto_20251117_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='API Key value', max_length=128, unique=True)),
                ('name', models.CharField(help_text='Name of the API Key', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of the API Key')),
                ('revoked', models.BooleanField(default=False, help_text='Whether the API Key is revoked or not')),
                ('player', models.ForeignKey(help_text='Owner of the API Key', on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'apikey',
                'managed': True,
            },
        ),
    ]
