# Generated by Django 5.2.8 on 2025-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0013_auto_20251117_1514")]

    operations = [
        migrations.AlterModelOptions(name="ball", options={"managed": True}),
        migrations.AlterModelOptions(name="ballinstance", options={"managed": True}),
        migrations.AddField(
            model_name="guildconfig",
            name="admin_command_synced",
            field=models.BooleanField(
                default=False, editable=False, help_text="True if slash admin commands are present in this server"
            ),
        ),
    ]
