# Generated by Django 6.0 on 2026-03-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0014_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group', max_length=64, unique=True)),
                ('balls', models.ManyToManyField(blank=True, help_text='Balls in this group', related_name='groups', to='bd_models.ball')),
            ],
            options={
                'db_table': 'group',
                'managed': True,
            },
        ),
    ]
