# Generated by Django 6.0 on 2026-05-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more")]

    operations = [
        migrations.AlterField(
            model_name="ballinstance",
            name="server_id",
            field=models.BigIntegerField(
                blank=True, help_text="Discord server ID where this ball was caught", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance", name="spawned_time", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="special",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.special"
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="trade_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ballinstance_trade_player_set",
                to="bd_models.player",
            ),
        ),
        migrations.AlterField(
            model_name="special",
            name="emoji",
            field=models.CharField(blank=True, help_text="A unicode character", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="ballinstance", index=models.Index(fields=["server_id"], name="ballinstanc_server__5c26aa_idx")
        ),
        migrations.AddIndex(
            model_name="ballinstance", index=models.Index(fields=["catch_date"], name="ballinstanc_catch_d_1707c8_idx")
        ),
        migrations.AddIndex(
            model_name="ballinstance",
            index=models.Index(fields=["server_id", "catch_date"], name="ballinstanc_server__a45274_idx"),
        ),
    ]
