# Generated by Django 6.0 on 2026-04-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more")]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="renderer",
            field=models.CharField(blank=True, help_text="Renderer to use", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="special",
            name="renderer",
            field=models.CharField(blank=True, help_text="Renderer to use", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="server_id",
            field=models.BigIntegerField(
                blank=True, help_text="Discord server ID where this ball was caught", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance", name="spawned_time", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="special",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.special"
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="trade_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ballinstance_trade_player_set",
                to="bd_models.player",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                (
                    "collection_card",
                    models.ImageField(
                        help_text="Image used when displaying balls", max_length=200, null=True, upload_to=""
                    ),
                ),
                ("renderer", models.CharField(blank=True, help_text="Renderer to use", max_length=128, null=True)),
                ("base_ball", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bd_models.ball")),
            ],
        ),
        migrations.AddField(
            model_name="ballinstance",
            name="variant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.variant"),
        ),
    ]
