# Generated by Django 6.0 on 2026-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more")]

    operations = [
        migrations.AddField(model_name="player", name="accepted_tos", field=models.BooleanField(default=False))
    ]
