# Generated by Django 6.0 on 2026-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0015_alter_ballinstance_server_id_and_more")]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="money",
            field=models.PositiveBigIntegerField(db_default=0, help_text="Money posessed by the player"),
        )
    ]
