# Generated by Django 6.0 on 2026-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0016_alter_player_money")]

    operations = [
        migrations.CreateModel(
            name="BallGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("countryballs", models.ManyToManyField(blank=True, related_name="groups", to="bd_models.ball")),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "db_table": "ballgroup",
                "managed": True,
            },
        )
    ]
