# Generated by Django 6.0 on 2026-07-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0017_ballgroup")]

    operations = [
        migrations.AlterField(
            model_name="ballinstance",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="balls",
                to="bd_models.player",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="player1",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.player"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trade_player2_set",
                to="bd_models.player",
            ),
        ),
        migrations.AlterField(
            model_name="tradeobject",
            name="ballinstance",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.ballinstance"
            ),
        ),
        migrations.AlterField(
            model_name="tradeobject",
            name="player",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.player"
            ),
        ),
    ]
