# Generated by Django 6.0 on 2026-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0017_ballgroup")]

    operations = [
        migrations.AddField(
            model_name="guildconfig",
            name="language",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Default language used to display countryballs in this server. "
                "Leave empty to use the bot's default language.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="language",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Preferred language used to display countryballs. "
                "Leave empty to use the server's or bot's default language.",
                max_length=8,
                null=True,
            ),
        ),
    ]
