# Generated by Django 6.0 on 2026-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0017_ballgroup")]

    operations = [
        migrations.AddField(
            model_name="guildconfig",
            name="manual_drop_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether players are allowed to use the drop command in this server"
            ),
        )
    ]
