# Generated by Django 6.0 on 2026-08-02 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0017_ballgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='bd_models.player')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ballinstance')),
            ],
            options={
                'db_table': 'voterecord',
                'ordering': ('-voted_at',),
                'managed': True,
                'indexes': [models.Index(fields=['player_id', 'voted_at'], name='voterecord_player__b479a1_idx')],
            },
        ),
    ]
