# Generated by Django 6.0 on 2026-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0018_guildconfig_manual_drop_enabled")]

    operations = [
        migrations.AddField(
            model_name="ballgroup",
            name="icon",
            field=models.ImageField(blank=True, help_text="256x256 PNG image", max_length=200, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="ballgroup",
            name="priority",
            field=models.FloatField(default=0, help_text="Priority for group list (higher is rightwards)"),
        ),
    ]
