# Generated by Django 6.0 on 2026-08-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0018_voterecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(unique=True)),
                ('application_id', models.BigIntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voteinteraction',
                'managed': True,
            },
        ),
    ]
