# Generated by Django 6.0 on 2026-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0018_guildconfig_manual_drop_enabled")]

    operations = [
        migrations.AddField(
            model_name="guildconfig",
            name="tips_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether tips are displayed below spawn messages in this server"
            ),
        )
    ]
