# Generated by Django 6.0 on 2026-07-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0019_guildconfig_language_player_language")]

    operations = [
        migrations.CreateModel(
            name="BallTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        help_text="Language code, must be one of the bot's enabled languages", max_length=8
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Translated name. Leave empty to fall back to the base name.",
                        max_length=48,
                        null=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Translated short name, used only when generating the card if the translated "
                            "name is too long."
                        ),
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "capacity_name",
                    models.CharField(
                        blank=True, help_text="Translated name of the countryball's capacity.", max_length=64, null=True
                    ),
                ),
                (
                    "capacity_description",
                    models.CharField(
                        blank=True,
                        help_text="Translated description of the countryball's capacity.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "ball",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="localizations", to="bd_models.ball"
                    ),
                ),
            ],
            options={
                "verbose_name": "translation",
                "verbose_name_plural": "translations",
                "db_table": "ball_translation",
                "managed": True,
                "unique_together": {("ball", "language")},
            },
        )
    ]
