DEFAULT_CARD_TEMPLATE = {
    "canvas_size": (1428, 2000),
    "layers": {
        "background": {
            "is_attribute": True,
            "is_image": True,
            "source": ["special_card", "countryball.cached_regime.background"],
            "anchor": (0, 0),
            "size": (1428, 2000),
        },
        "card_art": {
            "is_attribute": True,
            "is_image": True,
            "source": "countryball.collection_card",
            "anchor": (34, 261),
            "size": (1359, 731),
        },
        "title": {
            "is_attribute": True,
            "is_image": False,
            "source": ["countryball.short_name", "countryball.country"],
            "anchor": (50, 20),
            "text_font": "ArsenicaTrial-Extrabold.ttf",
            "text_font_size": 170,
            "text_stroke_width": 2,
            "text_stroke_fill": (0, 0, 0, 255),
        },
        "capacity_name": {
            "is_attribute": True,
            "is_image": False,
            "source": "countryball.capacity_name",
            "anchor": (100, 1050),
            "text_line_height": 100,
            "text_font": "Bobby Jones Soft.otf",
            "text_wrap": 26,
            "text_fill": (230, 230, 230, 255),
            "text_font_size": 110,
            "text_stroke_width": 2,
            "text_stroke_fill": (0, 0, 0, 255),
        },
        "capacity_description": {
            "is_attribute": True,
            "is_image": False,
            "source": "countryball.capacity_description",
            "anchor": (60, "capacity_name"),
            "text_line_height": 100,
            "text_font": "OpenSans-Semibold.ttf",
            "text_wrap": 32,
            "text_fill": (255, 255, 255, 255),
            "text_font_size": 75,
            "text_stroke_width": 1,
            "text_stroke_fill": (0, 0, 0, 255),
        },
        "health": {
            "is_attribute": True,
            "is_image": False,
            "source": "health",
            "anchor": (320, 1670),
            "text_line_height": 100,
            "text_font": "Bobby Jones Soft.otf",
            "text_wrap": 32,
            "text_fill": (237, 115, 101, 255),
            "text_font_size": 130,
            "text_stroke_width": 1,
            "text_stroke_fill": (0, 0, 0, 255),
        },
        "attack": {
            "is_attribute": True,
            "is_image": False,
            "source": "attack",
            "anchor": (1120, 1670),
            "text_line_height": 100,
            "text_font": "Bobby Jones Soft.otf",
            "text_wrap": 32,
            "text_fill": (252, 194, 76, 255),
            "text_anchor": "ra",
            "text_font_size": 130,
            "text_stroke_width": 1,
            "text_stroke_fill": (0, 0, 0, 255),
        },
        "lagg_credits": {
            "is_attribute": False,
            "is_image": False,
            "source": "Created by El Lagronn",
            "anchor": (30, 1870),
            "text_font": "arial.ttf",
            "text_line_height": 43,
            "text_fill": (255, 255, 255, 255),
            "text_font_size": 40,
            "text_stroke_width": 0,
        },
        "credits": {
            "is_attribute": True,
            "is_image": False,
            "source": "countryball.credits",
            "anchor": (30, "lagg_credits"),
            "text_font": "arial.ttf",
            "text_fill": (255, 255, 255, 255),
            "text_font_size": 40,
            "text_template": "Artwork author: $data",
            "text_stroke_width": 0,
        },
        "special_credits": {
            "is_attribute": True,
            "is_image": False,
            "source": "specialcard.credits",
            "anchor": (1398, 1870),
            "text_font": "arial.ttf",
            "text_fill": (255, 255, 255, 255),
            "text_font_size": 40,
            "text_template": "Special author: $data",
            "text_anchor": "ra",
            "text_stroke_width": 0,
        },
    },
}
